name: Create a tag

on:
    push:
        branches:
            - tag-setup

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Use desired version of NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: 18.15
                  cache: 'npm'

            - name: Build the release
              run: npm install && npm run release

            - name: Maybe create a tag
              run: bash bin/release.sh

            - name: Release
              if: ${{ env.TAG_CREATED == 'true' }}
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ env.BRAINSTORM_FORCE_RELEASE }}
                  body: ''
                  name: v${{ env.BRAINSTORM_FORCE_RELEASE }}
                  draft: false
                  files: force-ui.zip
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
